name: ValidateOrThrow.Nuget
on:
  push:
    branches:
      - main
      - master
    paths:
      - src/ValidateOrThrow/ValidateOrThrow.csproj
      - .github/workflows/PackageDeploy.ValiDateOrThrow.yml

permissions:
  contents: read

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: ValidateOrThrow.Nuget
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v1.0.1
        with:
          dotnet-version: 7.0.4 #${{ secrets.NET_VERSION }}
          path: src/ValidateOrThrow/ValidateOrThrow.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}